SiriusCashoutProcessorJob:
  Db:
    LogsConnString:
      settings-key: SiriusCashoutProcessorJob-LogsConnString
      types: [AzureTableStorage]
    DataConnString:
      settings-key: SiriusCashoutProcessorJob-DataConnString
      types: [AzureTableStorage]
  Cqrs:
    RabbitConnectionString:
      settings-key: RabbitSagas
      types: [ RabbitMq ]
  KeyVault:
    VaultBaseUrl:
      settings-key: SiriusCashoutProcessorJob-KeyVault-VaultBaseUrl
    ClientId:
      settings-key: SiriusCashoutProcessorJob-KeyVault-ClientId
    ClientSecret:
      settings-key: SiriusCashoutProcessorJob-KeyVault-ClientSecret
    PrivateKeyName:
      settings-key: SiriusCashoutProcessorJob-KeyVault-PrivateKeyName
  RetrySettings:
    NotEnoughBalanceRetryDelayInSeconds:
      settings-key: SiriusCashoutProcessorJob-NotEnoughBalanceRetryDelayInSeconds
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types: [AzureTableStorage]
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
SiriusApiServiceClient:
  GrpcServiceUrl:
    settings-key: SiriusApi-ServiceUrl
  ApiKey:
    settings-key: SiriusApi-ApiKey
  BrokerAccountId:
    settings-key: SiriusApi-BrokerAccountId
MatchingEngineClient:
  IpEndpoint:
    Port:
      settings-key: MatchingEngine-Port
    Host:
      settings-key: MatchingEngine-Host
AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl
  ExpirationPeriod:
    settings-key: AssetsServiceExpirationPeriod
OperationsServiceClient:
  ServiceUrl:
    settings-key: OperationsServiceUrl
